### ISSUE TITLE
configure Julia's PyCall to use the system Python?

### ISSUE THREAD

**Issue by stevengj** [gvarnavi/binder-env_py-3.8_jl-1.6_wl-12.2#2]
Since you've already set up an Anaconda Python installation in your Dockerfile, it would be nice to set up Julia to use this.

In your Dockerfile, it should be sufficient to set the `PYTHON` environment variable to `${NB_PYTHON_PREFIX}/bin/python` and then include PyCall in the `Pkg.add` command.  Also include PyCall (and maybe PyPlot) in Project.toml.

I'm thinking of setting up a binder environment for use in 18.335 and 18.303 this spring, and thought perhaps that I could base it on your script, since I would like to have both Python and Julia.

**Comment by gvarnavi** [comment]
Thanks - just pushed commit 5682ed9f39cb815a68df8eca99c9472f31659154 to add this (automatic build should finish in ~10').

With regards to 18.335/18.303, of-course feel free to base it on this script - although if you only need Python and Julia kernels, I suspect you can achieve this more easily using the configuration files [here](https://mybinder.readthedocs.io/en/latest/using/config_files.html).

**Comment by stevengj** [comment]
Actually, I realized that this is not necessary.  On Linux systems, PyCall uses the `python` in the `$PATH` by default, and so Docker already sets Anaconda Python as the default.

I took your advice and set up a binder environment using just the configuration files, and it seems to work well: https://github.com/mitmath/binder-env

**Comment by gvarnavi** [comment]
Great, glad to hear it works well.
Looking forward to taking/auditing the course in the spring!

**Comment by stevengj** [comment]
(So I would just revert https://github.com/gvarnavi/binder-env_py-3.8_jl-1.6_wl-12.2/commit/5682ed9f39cb815a68df8eca99c9472f31659154)

**Comment by gvarnavi** [comment]
Right, the rationale for leaving `PyCall` in the Dockerfile's `Pkg.add` command would be so that it's available in the default environment (which for example the WL's `ExternalEvaluate` resorts to), as opposed to the project-specific one. 

But I suppose that use-case is rather specific (and arguably of limited utility), and one could always activate the project environment inside an `ExternalEvaluate` call, as shown [here](https://github.com/gvarnavi/python-julia-wolfram-workflow-nbs/blob/main/02.cross-language-integration-wl.ipynb).

Pushed a new commit 2434d86e5ab56dc72cbaea742b1f50ea077d6278 to clean this up. Thanks
